import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { BoardContextProvider } from "@/components/providers/board-state-provider";
import { ModalProvider } from "@/components/providers/modal-provider";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <BoardContextProvider>
          <ModalProvider />
          {children}
        </BoardContextProvider>
      </body>
    </html>
  );
}
